name: Test

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - 'pypy-3.7'
        toxenv: [py]
        include:
          - python-version: '3.6'
            toxenv: typing
            os: ubuntu-latest
        exclude:
          # venv seems to be broken on pypy3 under Windows.
          - python-version: 'pypy-3.7'
            toxenv: py
            os: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade --upgrade-strategy=eager tox

      - name: Run tests
        if: matrix.toxenv == 'py'
        run: ./run-tests.sh -e py -- --ci --cov-report=xml

      - name: Run generic tests
        if: matrix.toxenv != 'py'
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        if: matrix.toxenv == 'py'
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false

# vim:set et sts=2:
